name: fitmetrics
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  audioplayers: ^6.0.0
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/fittintroimage.jpg
    - assets/images/logo.png


    - assets/images/meditation/movement_meditation.jpg
    - assets/images/meditation/music_meditation.jpg
    - assets/images/meditation/meditation_icon.jpg
    - assets/images/meditation/figures/rain.png
    - assets/images/meditation/figures/ocean.png
    - assets/images/meditation/figures/night.png
    - assets/images/meditation/figures/birds.png
    - assets/images/meditation/figures/morning.png
    - assets/images/meditation/figures/nature.png
    - assets/images/meditation/calmness/birds.png
    - assets/images/meditation/calmness/nature.png
    - assets/images/meditation/calmness/night.png
    - assets/images/meditation/calmness/ocean.png
    - assets/images/meditation/calmness/rain.png
    - assets/images/meditation/calmness/morning.png


    - assets/images/meditation/videos/rain.mp4
    - assets/images/meditation/videos/ocean.mp4
    - assets/images/meditation/videos/night.mp4
    - assets/images/meditation/videos/birds.mp4
    - assets/images/meditation/videos/morning.mp4
    - assets/images/meditation/videos/nature.mp4


    - assets/images/meditation/audio/rain.mp3
    - assets/images/meditation/audio/ocean.mp3
    - assets/images/meditation/audio/night.mp3
    - assets/images/meditation/audio/birds.mp3
    - assets/images/meditation/audio/morning.mp3
    - assets/images/meditation/audio/nature.mp3

