// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjS9_rYJJQJ5BP_asz3OsDIbMevAb6Ah4',
    appId: '1:934781705613:web:b7d7bdc1fbda55e5c9b1c4',
    messagingSenderId: '934781705613',
    projectId: 'fitmetrics-kapil',
    authDomain: 'fitmetrics-kapil.firebaseapp.com',
    storageBucket: 'fitmetrics-kapil.firebasestorage.app',
    measurementId: 'G-M6C23SF5JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR5NAy3xE4Nnk4_Juh9eVvNqv52piiS9g',
    appId: '1:934781705613:android:b5c1f50f649dc3d9c9b1c4',
    messagingSenderId: '934781705613',
    projectId: 'fitmetrics-kapil',
    storageBucket: 'fitmetrics-kapil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9LipBYvAvIQwaIQ-gtGl5zCsHRtdwcRE',
    appId: '1:934781705613:ios:ca4f2405753e60aac9b1c4',
    messagingSenderId: '934781705613',
    projectId: 'fitmetrics-kapil',
    storageBucket: 'fitmetrics-kapil.firebasestorage.app',
    iosBundleId: 'com.example.fitmatricsApp',
  );
}
